"""
Django settings for cfdi_timbrador project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e4jf$#99!6i0ns=cvfe4z5072qxx7-g%qud49$rziab2#g0zj-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*'
]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'applications.timbrado_edicom',
    'applications.knzl',
    'applications.api_cfdi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cfdi_timbrador.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cfdi_timbrador.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


CRONJOBS = [
    ('*/2 * * * *', 'applications.timbrado_edicom.jobs.cron.my_cron_job')
]

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'impapx2',
        'USER': 'root',
        'PASSWORD': 'sys',
        'HOST': '10.10.1.229',
        'PORT': 3306 ,
        'OPTIONS': {'ssl': False},
        #'OPTIONS': {'ssl_mode': 'DISABLED'},
    },
     'rh': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sx_rh',
        'USER': 'root',
        'PASSWORD': 'sys',
        'HOST': '10.10.1.229',
        'PORT': 3306 ,
        'OPTIONS': {'ssl': False},
        #'OPTIONS': {'ssl_mode': 'DISABLED'},
    },
    'paper': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'paperx2',
        'USER': 'root',
        'PASSWORD': 'sys',
        'HOST': '10.10.1.229',
        'PORT': 3306 ,
        'OPTIONS': {'ssl': False},
        #'OPTIONS': {'ssl_mode': 'DISABLED'},
    },
    'mobix': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lx_mobix',
        'USER': 'root',
        'PASSWORD': 'sys',
        'HOST': '10.10.1.229',
        'PORT': 3306 ,
        'OPTIONS': {'ssl': False},
        #'OPTIONS': {'ssl_mode': 'DISABLED'},
    },
    'siipapx': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'siipapx',
        'USER': 'root',
        'PASSWORD': 'sys',
        'HOST': '10.10.1.229',
        'PORT': 3306 ,
        'OPTIONS': {'ssl': False},
        #'OPTIONS': {'ssl_mode': 'DISABLED'},
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es-mx'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
